### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by inikolaev** [lgwillmore/typemock#12]
Hi! 

What's the status of this project?
I saw a note that it's still **alfa** and there haven't been any changes for quite a while already.
Any plans to continue working on it?

**Comment by lgwillmore** [comment]
Hi there - Ya, I am afraid I have moved away from python development, and so the pain of not having type safe mocks has gone away for me. Unlikely to pick it up I think.

**Comment by lgwillmore** [comment]
Closing as answered.
